$(document).ready(function(){
    $('#tnc').scroll(function(){
        scrollheight=$('#tnc').scrollTop();
        if(scrollheight>500)
        {
            $('#agree').removeAttr('disabled');
        }
    });
});